### PR TITLE
Fix 'Extra metrics' kwalitee problems

### PR DESCRIPTION
**Pull request by jhunt**
per http://cpants.cpanauthors.org/dist/Crypt-SaltedHash

### CODE REVIEW

**Comment by karenetheridge** [comment]
`use 5.006` in the source won't resolve the 'declared minimum perl version' kwalitee metric. It needs to be in the metadata itself.

**Comment by karenetheridge** [comment]
I can take on maintenance of this distribution, as @gshank has moved on from Campus Explorer, but it appears that primary permissions are held by ESSKAR (Sascha Kiefer).  Gerda, is Sascha still around? should I contact the PAUSE admins to massage the permissions bits?

**Comment by jhunt** [comment]
I am aware that the `use 5.006` construct won't fix the minimum version thing, but I'm not familiar enough with Dist::Zilla to fix that one.

**Comment by karenetheridge** [comment]
@filefrog dist.ini just needs this added:  `[MinimumPerl]`

**Comment by jhunt** [comment]
Adding; I'll re-submit the PR when it's done.

**Comment by karenetheridge** [comment]
@filefrog if you `git push --force` to your branch, this PR will update automatically with the changes.

**Comment by jhunt** [comment]
@karenetheridge I believe it already updated?

**Comment by karenetheridge** [comment]
@gshank can we get permissions switched over?

**Comment by gshank** [comment]
I just have maint, so I don’t think I can change permissions. I’ll release
it if you put it someplace I can get to it, or else you can contact the
owner?

Gerda

**Comment by karenetheridge** [comment]
>  I’ll release it if you put it someplace I can get to it

I'm not sure which 'it' you are thinking of here :)

Do you have a contact for the owner?

**Comment by jhunt** [comment]
Any movement on this?  (Just noticed this PR this evening, trying to prune my outstandings)

**Pull request closed without merging**
